techpack: display: Fix uninitialized dsi_display warning
../techpack/display/msm/sde/sde_connector.c:126:6: error: variable
'dsi_display' is used uninitialized whenever 'if' condition is false
[-Werror,-Wsometimes-uninitialized]
        if (c_conn->connector_type == DRM_MODE_CONNECTOR_DSI) {
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../techpack/display/msm/sde/sde_connector.c:182:14: note: uninitialized
use occurs here
        if (!strcmp(dsi_display->display_type, "primary")){
                    ^~~~~~~~~~~

Change-Id: I9944baf14c55885a0ce62425c576fba945050674